# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: PFITS+
subtitle: "Planet Formation in the Southwest +"
email:
description: "Theoretical and computational research into protoplanetary disk evolution, planet formation, and the multiscale physics involved"
  # >- this means to ignore newlines until "baseurl:"
# twitter_username: username
github_username: pfitsplus
minimal_mistakes_skin: dirt
search: true
logo: "/assets/images/logo.png"
favicon: "/assets/images/favicon.ico"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /news/page:num/
timezone: US/Mountain # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Analytics
analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "" # Replace this with your ID
    anonymize_ip         : false

# Reading Files
include:
  - _pages
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  research:
    output: true
    permalink: /:collection/:path/
  team:
    output: true
    permalink: /:collection/:path/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Site Author
author:
  name: "PFITS+"
  avatar: "/assets/images/logo.webp"
  bio: "Planet Formation in the Southwest (plus Iowa and Alabama)"
  location: "Las Cruces, NM</br>&emsp;&ensp;Tucson, AZ</br>&emsp;&ensp;Mountain View, CA</br>&emsp;&ensp;Ames, IA</br>&emsp;&ensp;Tuscaloosa, AL"
  links:
    # - label: "Website"
    #   icon: "fas fa-fw fa-link"
    #   url: "https://"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/pfitsplus"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

# Site Footer
footer:
  links:
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/pfitsplus"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      header:
        overlay_color: "#e6ad00"
  # _research
  - scope:
      path: "_research"
      type: research
    values:
      layout: single
      header:
        overlay_color: "#e6ad00"
      excerpt: ""
      share: true
      sidebar:
        nav: "research"
      toc: true
      toc_sticky: true
  # _team
  - scope:
      path: "_team"
      type: team
    values:
      layout: single
      header:
        overlay_color: "#e6ad00"
      excerpt: ""
      share: true

# Archive Settings (GitHub Pages)
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
